# Generated by Django 5.1.2 on 2024-11-06 01:53

from django.db import migrations


def populate_status(apps, schemaeditor):
    entries = {
        "To Do": "An issue for which work has not yet begun",
        "In Progress": "An issue actively being worked on",
        "Done": "A completed issue"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status = Status(name=key, description=value)
        status.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_auto_20241105_1953'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
